name: bmi_first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/scale.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/logo.png
    - assets/images/body.png


flutter_native_splash:
  color: "#F5F7FA"
  image: assets/images/logo.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
